server:
  port: 8085
spring:
  application:
    name: envios-service
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{traceId:-sin-trace}] %-5level %logger{36} - %msg%n"
  level:
    root: info
