server:
  port: 8084
spring:
  application:
    name: pagos-service
  datasource:
    url: jdbc:h2:mem:pagosdb
  jpa:
    hibernate:
      ddl-auto: update
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{traceId:-sin-trace}] %-5level %logger{36} - %msg%n"
  level:
    root: info
